[workspace]
members = ["crates/harmony-core", "crates/harmony-engine", "crates/noctave"]
resolver = "2"

[workspace.package]
version = "0.1.0-beta.1"
edition = "2021"
license = "MIT"
rust-version = "1.85"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
lto = "thin"
strip = true

